export const data = [
  {
    address1: '996 Queen Street, Toronto, ON',
    address2: '',
    zipcode: 'M4M 1K1',
    type: 'House',
    price: 570000,
    floor: 2,
  },
  {
    address1: '665 Bloor Street West, Toronto, ON',
    address2: '',
    zipcode: 'M6G 1L1',
    type: 'House',
    price: 779300,
    floor: 1,
  },
  {
    address1: '7 Triller Ave, Toronto, ON',
    address2: '',
    zipcode: 'M6K 3B7',
    type: 'House',
    price: 883300,
    floor: 3,
  },
  {
    address1: '586 Parliament Street, Toronto, ON',
    address2: '',
    zipcode: 'M4X 1P8',
    type: 'House',
    price: 580000,
    floor: 2,
  },
  {
    address1: '700 University ave, Toronto, ON',
    address2: '',
    zipcode: 'M5G 1Z5',
    type: 'House',
    price: 350000,
    floor: 2,
  },
  {
    address1: '798 Richmond Street West, Toronto, ON',
    address2: 'Akelius',
    zipcode: 'M6J 3N7',
    type: 'Apartment',
    price: 460000,
    floor: 99999999,
  },
  {
    address1: '78 Victor ave, Toronto, ON',
    address2: '',
    zipcode: 'M4K 1A8',
    type: 'House',
    price: 665000,
    floor: 2,
  },
  {
    address1: '411-1 Bedford Road, Toronto, ON',
    address2: '',
    zipcode: 'M5R 2J7',
    type: 'House',
    price: 160000,
    floor: 1,
  },
  {
    address1: '45 Morse Street, Toronto, ON',
    address2: '',
    zipcode: 'M4M 2P7',
    type: 'House',
    price: 130000,
    floor: 2,
  },
  {
    address1: '53 Palmerston ave, Toronto, ON',
    address2: '',
    zipcode: 'M6J 2J2',
    type: 'Houes',
    price: 300000,
    floor: 22,
  },
  {
    address1: '404 Spadina ave, Toronto, ON',
    address2: '',
    zipcode: 'M5T 2G7',
    type: 'House',
    price: 220000,
    floor: 2,
  },
  {
    address1: '665 Queen Street West, Toronto, ON',
    address2: '',
    zipcode: 'M0T 1E6',
    type: 'House',
    price: 499000,
    floor: 0,
  },
  {
    address1: '43 Baldwin street, Toronto, ON',
    address2: '',
    zipcode: 'M5T 1L1',
    type: 'House',
    price: 399000,
    floor: 2,
  },
  {
    address1: '53 Palmerston ave, Toronto, ON',
    address2: '',
    zipcode: 'M6J 2J2',
    type: 'House',
    price: 300000,
    floor: 1,
  },
  {
    address1: '321 Sherbourne St, Toronto, ON',
    address2: 'Garden View',
    zipcode: 'M5A 2S4',
    type: 'Apartment',
    price: 700000,
    floor: 2,
  },
  {
    address1: '525 Richmond Street West, Toronto, ON',
    address2: '525 Richmond',
    zipcode: 'M5V 1Y5',
    type: 'Apartment',
    price: 599000,
    floor: 4,
  },
  {
    address1: '15 Dundonald Street, Toronto, ON',
    address2: '15 Dundonald ',
    zipcode: 'M4Y 1k4',
    type: 'Apartment',
    price: 699000,
    floor: 19,
  },
  {
    address1: '1101 Bay Street, Toronto, ON',
    address2: '1101 Bay',
    zipcode: 'M5S 2W8',
    type: 'Apartment',
    price: 1000000,
    floor: 29,
  },
  {
    address1: '57 Charles Street, Toronto, ON',
    address2: 'Vertica Resident',
    zipcode: 'M5S 2X1',
    type: 'Apartment',
    price: 299000,
    floor: 3,
  },
  {
    address1: '570 Bay Street, Toronto, ON',
    address2: 'Motion',
    zipcode: 'M5G 0B2',
    type: 'Apartment',
    price: 477000,
    floor: 650000,
  },
  {
    address1: '252 Victoria Street, Toronto, ON',
    address2: 'Velocity at the Square',
    zipcode: 'M5B 0A3',
    type: 'Apartment',
    price: 800000,
    floor: 24,
  },
  {
    address1: '11 Church Street, Toronro, ON',
    address2: 'Capreit',
    zipcode: 'M5E 1W1',
    type: 'Apartment',
    price: 1200000,
    floor: 27,
  },
  {
    address1: '55 Mill Street, Toronto, ON',
    address2: 'The Distillery Historic District',
    zipcode: 'M5A 3C4',
    type: 'Apartment',
    price: 2000000,
    floor: 45,
  },
  {
    address1: '50 John Street, Toronto, ON',
    address2: 'The Resemont Residences',
    zipcode: 'M5V 3T5',
    type: 'Residence',
    price: 1500000,
    floor: 39,
  },
  {
    address1: '300 Front Street West, Toronto, ON',
    address2: 'Atlas Suites CN Tower and Convention Center',
    zipcode: 'M5V 0E9',
    type: 'Apartment',
    price: 3000000,
    floor: 50,
  },
  {
    address1: '371 Front Street West, Toronto, ON',
    address2: 'Three Towers Residential',
    zipcode: 'M5V 3S8',
    type: 'Apartment',
    price: 2100000,
    floor: 32,
  },
  {
    address1: '50 Portland Street, Toronto, ON',
    address2: 'Fifty On The Park',
    zipcode: 'M5V 2M7',
    type: 'Apartment',
    price: 1100000,
    floor: 22,
  },
  {
    address1: '33 Davisville Ave, Toronto, ON',
    address2: 'Davisville Village apartments',
    zipcode: 'M4S 2Y9',
    type: 'Apartment',
    price: 890000,
    floor: 11,
  },
  {
    address1: '173 Duplex  Ave, Toronto, ON',
    address2: 'DelSuites',
    zipcode: 'M5P 2A8',
    type: 'Apartment',
    price: 770000,
    floor: 9,
  },
  {
    address1: '780 Eglinton Ave, Toronto, ON',
    address2: 'Forest Hill Residences Rental Apartment',
    zipcode: 'M5N 1E9',
    type: 'Apartment',
    price: 199000,
    floor: 4,
  },
]
